API gateway and auth service
Pigeons-Inc/pigeon pull request #28
Opened 2022-07-08 22:13 UTC by Secret333Boy

2022-07-14 19:47 UTC, Secret333Boy commented on server/microservices/auth/tests/app.test.ts
> +        'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdlZGVhMDAxLWM4ZWEtNDFiYy04N2FkLTg2MjNmZTVkZWZlOCIsImVtYWlsIjoiYWRhZGFkYWRAZ21haWwuY29tIiwiaGFzaCI6ImFkYWRhZGFkYSIsImlzQWN0aXZhdGVkIjp0cn
It is used in tests only

2022-07-23 17:37 UTC, GluterusMaximus requested changes

2022-07-23 17:37 UTC, GluterusMaximus commented on server/microservices/auth/src/models/sequelize/User.ts
> +    unique: true,
Shouldnt be unique

2022-07-23 17:37 UTC, GluterusMaximus commented on server/microservices/auth/src/models/sequelize/TokenStore.ts
> +});
Creates a redundant column UserId
![image](https://user-images.githubusercontent.com/80482122/180616217-4380887b-1deb-46bc-b127-e94fe156e976.png)

2022-07-25 07:54 UTC, GluterusMaximus commented on server/microservices/auth/src/controllers/AuthController.ts
> +  }
Okay, this sort of request probably shouldn't occur under normal curcumstances, so the system behaves as expected.

2022-07-25 08:24 UTC, Secret333Boy commented on server/microservices/gateway/src/app.ts
> +
It is client's task, not gateway's. Client should manage its tokens by itself. Gateway needs only to validate and pass requests to other services

2022-07-25 09:36 UTC, GluterusMaximus commented on server/microservices/gateway/src/app.ts
> +
Got it

2022-07-26 17:34 UTC, Secret333Boy commented on server/microservices/auth/src/controllers/AuthController.ts
> +  @Post('/validateCredentials')
Because we need to send body. GET method can't send body in most cases: https://stackoverflow.com/questions/45550863/async-get-request-with-body-from-browser/45550919#45550919

2022-07-26 18:13 UTC, Secret333Boy commented on server/microservices/auth/src/repository/sequelize.ts
> +const password = process.env.POSTGRES_PASSWORD || 'postgres';
Fixed in 45e16ae9a077e03d699f9b3f7d919b6c74185284

2022-07-26 18:14 UTC, Secret333Boy commented on server/microservices/auth/src/middlewares/checkAPISecretMiddleware.ts
> +  res.status(403).end();
Fixed in 45e16ae9a077e03d699f9b3f7d919b6c74185284

2022-07-26 18:15 UTC, Secret333Boy commented on server/microservices/auth/src/models/sequelize/User.ts
> +  },
Fixed in 45e16ae9a077e03d699f9b3f7d919b6c74185284

2022-07-26 18:15 UTC, Secret333Boy commented on server/microservices/auth/src/controllers/AuthController.ts
> +  public async activate(@Query() id = '') {
Fixed in 45e16ae9a077e03d699f9b3f7d919b6c74185284

2022-07-26 18:15 UTC, Secret333Boy commented on server/microservices/auth/src/services/TokenService.ts
> +    const finded = await TokenStore.findOne({ where: { id: user.id } });
Fixed in 45e16ae9a077e03d699f9b3f7d919b6c74185284

2022-07-26 18:15 UTC, Secret333Boy commented on server/microservices/auth/src/models/sequelize/User.ts
> +    unique: true,
Fixed in 45e16ae9a077e03d699f9b3f7d919b6c74185284

2022-07-26 18:15 UTC, Secret333Boy commented on server/microservices/auth/src/models/sequelize/TokenStore.ts
> +});
Fixed in 45e16ae9a077e03d699f9b3f7d919b6c74185284

2022-07-27 11:16 UTC, GluterusMaximus commented on server/microservices/auth/src/controllers/AuthController.ts
> +  @Post('/validateCredentials')
Got it

2022-07-27 11:19 UTC, Secret333Boy commented on server/microservices/auth/src/controllers/AuthController.ts
> +  @Put('/activate')
Fixed in https://github.com/Pigeons-Inc/pigeon/commit/45e16ae9a077e03d699f9b3f7d919b6c74185284

2022-07-27 11:22 UTC, GluterusMaximus approved these changes
Looks good

2022-07-30 09:32 UTC, GeniusDP approved these changes
Ну вроде норм всё.

2022-07-30 09:32 UTC, GeniusDP commented on .github/workflows/sonar.yml
> +          API_SECRET: 12345678
Так, ну это понятно

2022-07-30 09:32 UTC, GeniusDP commented on .github/workflows/node.js.yml
> +          node-version: 16.x
Оу, хордкод лучше, чем переменный окружения? Панимаю.

2022-07-30 09:32 UTC, GeniusDP commented on .github/workflows/node.js.yml
> +        ports:
Хахаха. Всё postgres.)

2022-07-30 09:32 UTC, GeniusDP commented on .github/workflows/sonar.yml
> +
Это что-то типа про автовосстановление? Если так, то круто. Если нет, то тоже супер.

2022-07-30 09:32 UTC, GeniusDP commented on server/microservices/auth/package-lock.json
> +      "resolved": "https://registry.npmjs.org/@typescript-eslint/eslint-plugin/-/eslint-plugin-5.30.6.tgz",
какия-то страннннные весчи. Будем считать, что работает.

2022-07-30 09:32 UTC, GeniusDP commented on server/microservices/auth/src/app.ts
> +
Кст, а не пофиг ли тут на async? Я вот не знаю.

2022-07-30 09:32 UTC, GeniusDP commented on server/microservices/auth/src/controllers/AuthController.ts
> +        path: '/api',
Ха-ха-ха. Ну да, ну да. У нас ведь всегда в месяце 30 дней, верно?)

2022-07-30 09:32 UTC, GeniusDP commented on server/microservices/auth/src/middlewares/checkAPISecretMiddleware.ts
> +  res.status(403).json(errorResponse);
О. Норм валидация. Если всё норм, то идём дальше, иначе кидаем ексепшн.

2022-07-30 09:32 UTC, GeniusDP commented on server/microservices/auth/src/repository/sequelize.ts
> +});
logging false?)

2022-07-30 09:32 UTC, GeniusDP commented on server/microservices/auth/src/repository/sequelize.ts
> +});
Хотя в принципе пофиг. Если упадёт, то ей ужелоги не помогут.

2022-07-30 09:32 UTC, GeniusDP commented on server/microservices/auth/src/utils/Validator.ts
> +    return this;
Ну вот и первый смысловой коммент от меня. 
Было бы норм в констанату вынести регулярку.

2022-07-30 09:32 UTC, GeniusDP commented on server/microservices/auth/src/utils/Validator.ts
> +    return this;
Юююхуууу! Сколько ифов.

2022-07-30 09:32 UTC, GeniusDP commented on server/microservices/auth/tests/AuthController.test.ts
> +    await expect(controller.ping()).resolves.toEqual({ message: 'pong' });
пинг-понг.)

2022-07-30 09:43 UTC, Secret333Boy commented on .github/workflows/node.js.yml
> +          node-version: 16.x
We will use only node 16.x

2022-07-30 09:43 UTC, Secret333Boy commented on .github/workflows/node.js.yml
> +        ports:
:)

2022-07-30 09:44 UTC, Secret333Boy commented on .github/workflows/sonar.yml
> +
Kind-of, we are waiting postgres to start here before proceeding to the next step

2022-07-30 09:46 UTC, Secret333Boy commented on server/microservices/auth/package-lock.json
> +      "resolved": "https://registry.npmjs.org/@typescript-eslint/eslint-plugin/-/eslint-plugin-5.30.6.tgz",
There is no need to check this file, it is auto-generated by npm

2022-07-30 09:46 UTC, Secret333Boy commented on server/microservices/auth/package-lock.json
> +      "resolved": "https://registry.npmjs.org/@typescript-eslint/eslint-plugin/-/eslint-plugin-5.30.6.tgz",
Of course it works, we have a lot of tests)

2022-07-30 09:48 UTC, Secret333Boy commented on server/microservices/auth/src/app.ts
> +
Better to have, just in case not to forget about it

2022-07-30 09:52 UTC, Secret333Boy commented on server/microservices/auth/src/controllers/AuthController.ts
> +        path: '/api',
Our refresh token dies after 30 days, not 1 month :)

2022-07-30 09:52 UTC, Secret333Boy commented on server/microservices/auth/src/controllers/AuthController.ts
> +        path: '/api',
Therefore, it will be constant

2022-07-30 09:53 UTC, Secret333Boy commented on server/microservices/auth/src/middlewares/checkAPISecretMiddleware.ts
> +  res.status(403).json(errorResponse);
Thanks :)

2022-07-30 09:54 UTC, Secret333Boy commented on server/microservices/auth/src/repository/sequelize.ts
> +});
We will make logging later, it isn't really needed right now

2022-07-30 09:57 UTC, Secret333Boy commented on server/microservices/auth/src/utils/Validator.ts
> +    return this;
"Magic string"? Ok, will be fixed

2022-07-30 09:59 UTC, Secret333Boy commented on server/microservices/auth/src/utils/Validator.ts
> +    return this;
It is ok, validation))

2022-07-30 09:59 UTC, Secret333Boy commented on server/microservices/auth/tests/AuthController.test.ts
> +    await expect(controller.ping()).resolves.toEqual({ message: 'pong' });
:)

2022-07-31 09:30 UTC, merged