Email service
Pigeons-Inc/pigeon pull request #30
Opened 2022-07-22 15:08 UTC by GluterusMaximus

Closes #20

2022-07-31 10:38 UTC, Secret333Boy requested changes
There are some possible improvements

2022-07-31 10:38 UTC, Secret333Boy commented on server/microservices/email/src/index.ts
> +});
Use Node.js cluster

2022-07-31 10:38 UTC, Secret333Boy commented on server/microservices/email/src/controllers/SendController.ts
> +}
Maybe it would be better to have:
POST /send (for sending any type of email)
POST /send/activation
POST /send/reset
It will be easier to use this service if we will be willing to add some more functionality with sending emails. 
Also, it is safe because only our services can send requests to this service (only they have API secret)

2022-07-31 10:38 UTC, Secret333Boy commented on server/microservices/email/src/interfaces/SendMailOptions.ts
> +}
Don't we have this interface in @types/nodemailer?

2022-07-31 10:38 UTC, Secret333Boy commented on server/microservices/email/src/services/SendService.ts
> +    return this.sendMail({ to, subject, html });
What if mail client can't show html? Therefore, we need to specify text

2022-07-31 10:38 UTC, Secret333Boy commented on server/microservices/email/src/services/SendService.ts
> +    `;
What about creating separate .html file and loading it here? It would probably be easier to customize it

2022-08-01 10:52 UTC, GluterusMaximus commented on server/microservices/email/src/interfaces/SendMailOptions.ts
> +}
TO is required, also the lib one has a lot of additional parameters

2022-08-01 11:00 UTC, GluterusMaximus commented on server/microservices/email/src/index.ts
> +});
You mean run many intances of the service as workers? You didn't do it in auth service, so i assumed it wasnt needed :) (or did you?). Don't have any experience with node clustering tbh

2022-08-01 11:04 UTC, Secret333Boy commented on server/microservices/email/src/index.ts
> +});
I don't have it in auth service because it is stateful (if several proccesses will try to access db, something bad might happend). I did it in gateway, check it [here](https://github.com/Pigeons-Inc/pigeon/blob/master/server/microservices/gateway/src/index.ts)

2022-08-01 11:07 UTC, Secret333Boy commented on server/microservices/email/src/interfaces/SendMailOptions.ts
> +}
If we have a lot additional parameters, we can use Pick<type, ...parameters>. Check it [here](https://www.typescriptlang.org/docs/handbook/utility-types.html#picktype-keys)

2022-08-01 11:35 UTC, GluterusMaximus commented on server/microservices/email/src/index.ts
> +});
Makes sense, will look at gateway

2022-08-01 12:45 UTC, GluterusMaximus commented on server/microservices/email/src/interfaces/SendMailOptions.ts
> +}
Tried to implement it, the build fails:
![image](https://user-images.githubusercontent.com/80482122/182150371-c7d9bf0b-17ef-4dde-b045-2a8e9f8565cb.png)

As I understand, the only solution is to duplicate the type dependencies in the repo, which is what I did from the strat basically
[(lukeautry/tsoa/issues/340)]

2022-08-01 16:45 UTC, GluterusMaximus commented on server/microservices/email/src/controllers/SendController.ts
> +}
Fixed in [9a1a7d4](https://github.com/Pigeons-Inc/pigeon/pull/30/commits/9a1a7d40e2fdd2ad8ee4b91473e0499272eb6be0)

2022-08-01 16:46 UTC, GluterusMaximus commented on server/microservices/email/src/index.ts
> +});
Fixed in [c7c3dee](https://github.com/Pigeons-Inc/pigeon/pull/30/commits/c7c3deee2ba43ae929cd7322e74102ed435e7ce4)

2022-08-01 16:46 UTC, GluterusMaximus commented on server/microservices/email/src/services/SendService.ts
> +    `;
Fixed in [80096e1](https://github.com/Pigeons-Inc/pigeon/pull/30/commits/80096e136d546bfa5de8fe8dd8c3837b38a8b8aa)

2022-08-01 16:46 UTC, GluterusMaximus commented on server/microservices/email/src/services/SendService.ts
> +    return this.sendMail({ to, subject, html });
FIxed in [80096e1](https://github.com/Pigeons-Inc/pigeon/pull/30/commits/80096e136d546bfa5de8fe8dd8c3837b38a8b8aa)

2022-08-01 16:48 UTC, GluterusMaximus commented on server/microservices/email/src/controllers/SendController.ts
> +}
Fixed in [9a1a7d4](https://github.com/Pigeons-Inc/pigeon/pull/30/commits/9a1a7d40e2fdd2ad8ee4b91473e0499272eb6be0)

2022-08-01 16:49 UTC, GluterusMaximus commented on server/microservices/email/src/services/SendService.ts
> +    return this.sendMail({ to, subject, html });
Fixed in [80096e1](https://github.com/Pigeons-Inc/pigeon/pull/30/commits/80096e136d546bfa5de8fe8dd8c3837b38a8b8aa)

2022-08-02 10:56 UTC, Secret333Boy commented on server/microservices/email/src/interfaces/SendMailOptions.ts
> +}
OK, not critical

2022-08-02 11:31 UTC, Secret333Boy approved these changes
Looks good except 1 redundant if. Fix and merge :)

2022-08-02 11:31 UTC, Secret333Boy commented on server/microservices/email/src/index.ts
> +if (+process.version.split('.')[0] < 16)
Redundant if?

2022-08-02 11:47 UTC, Secret333Boy approved these changes
Looks good

2022-08-02 11:49 UTC, GluterusMaximus commented on server/microservices/email/src/index.ts
> +if (+process.version.split('.')[0] < 16)
Fixed

2022-08-13 12:36 UTC, merged