Index testing
Pigeons-Inc/pigeon pull request #37
Opened 2022-08-05 10:09 UTC by GluterusMaximus

2022-08-05 10:21 UTC, Secret333Boy requested changes
You forgot to enable this tests. Just remove index files from exclusions in [this](https://github.com/Pigeons-Inc/pigeon/blob/master/sonar-project.properties) file

2022-08-05 17:40 UTC, GluterusMaximus commented
> You forgot to enable this tests. Just remove index files from exclusions in [this](https://github.com/Pigeons-Inc/pigeon/blob/master/sonar-project.properties) file

Done

2022-08-06 10:12 UTC, Secret333Boy submitted a review, later dismissed
Looks good!

2022-08-13 12:35 UTC, Secret333Boy approved these changes

2022-08-13 12:39 UTC, merged