Error middleware and validator
Pigeons-Inc/pigeon pull request #56
Opened 2022-08-08 12:21 UTC by Secret333Boy

Closes #40

2022-08-08 16:03 UTC, GluterusMaximus requested changes

2022-08-08 16:03 UTC, GluterusMaximus commented on server/microservices/chat/src/utils/Validator.ts
> +    neededPermissions: Permission[]
Should be strings

2022-08-08 16:40 UTC, Secret333Boy commented on server/microservices/chat/src/utils/Validator.ts
> +    neededPermissions: Permission[]
Fixed in 69304e9

2022-08-09 11:45 UTC, GluterusMaximus approved these changes
good

2022-08-09 11:45 UTC, merged