Profile service
Pigeons-Inc/pigeon pull request #62
Opened 2022-08-15 13:11 UTC by Secret333Boy

2022-08-19 19:00 UTC, Secret333Boy commented
I've turned off checking coverage because some tests had conflicts with new code and I had to delete some tests

2022-08-21 11:32 UTC, GluterusMaximus requested changes
Remove pendin profiles

2022-08-21 11:32 UTC, GluterusMaximus commented on server/microservices/profile/src/controllers/ProfileController.ts
> +      res.sendStatus(201);
Shouldn't we return the created profile to display it immediately

2022-08-21 11:32 UTC, GluterusMaximus commented on server/microservices/profile/src/services/ProfileService.ts
> +    return profile;
Returning raw database intances is bad (Nosov said so :) ). Probably better to use a dto

2022-08-21 11:32 UTC, GluterusMaximus commented on server/microservices/profile/src/services/ProfileService.ts
> +    if (body.tag) profile.tag = body.tag;
No tag validation

2022-08-21 11:32 UTC, GluterusMaximus commented on server/microservices/profile/src/routes/profileRouter.ts
> +profileRouter.put('/', profileController.updateProfile);
Shouldn't this be a patch request (If no name in the request body for example, dont change the name)

2022-08-21 11:32 UTC, GluterusMaximus commented on server/microservices/profile/src/services/ProfileService.ts
> +    const id = (<{ id: string }>jwt.decode(token))?.id;
What if no token?

2022-08-21 11:32 UTC, GluterusMaximus commented on server/microservices/profile/src/models/interfaces/ProfileContacts.ts
> +}
Why not store the contacts in the profile

2022-08-21 11:32 UTC, GluterusMaximus commented on server/microservices/profile/src/services/ProfileService.ts
> +      throw ApiError.badRequest('Missing some fields');
Probably needs more thorough validation (name length, tag length, whether birthdate is a valid date etc.)

2022-08-21 11:32 UTC, GluterusMaximus commented on server/microservices/profile/src/services/ProfileService.ts
> +    profile: IProfile,
why not just pass the profile id

2022-08-21 12:09 UTC, Secret333Boy commented on server/microservices/profile/src/services/ProfileService.ts
> +    return profile;
Do you mean 
```
res.status(200).json(JSON.parse(JSON.stringify(profile)))
```
?

2022-08-21 12:11 UTC, Secret333Boy commented on server/microservices/profile/src/services/ProfileService.ts
> +    return profile;
It is already serialized by res.json() and has only what we need to send

2022-08-21 12:14 UTC, Secret333Boy commented on server/microservices/profile/src/services/ProfileService.ts
> +    const id = (<{ id: string }>jwt.decode(token))?.id;
In this situation we would have 403 Forbidden in gateway

2022-08-21 12:18 UTC, Secret333Boy commented on server/microservices/profile/src/models/interfaces/ProfileContacts.ts
> +}
Because of many-to-many relation. And also we need to segregate Profile and Contact dtos

2022-08-22 09:38 UTC, GluterusMaximus commented on server/microservices/profile/src/services/ProfileService.ts
> +    return profile;
No, I meant we need to explicitly control what object is sent as a response (what fields etc.)
Something like
```suggestion
    return res.status(200).json(new ProfileResponseDTO(profile));
```
so for example utility fields that we don't need are not included in the response (e.g. __version in MongoDB)
Once again, this is what Nosov recommended

2022-08-22 09:38 UTC, GluterusMaximus commented on server/microservices/profile/src/services/ProfileService.ts
> +    return profile;
I tried to implement this in chat service so take a look if you want

2022-08-22 09:41 UTC, GluterusMaximus commented on server/microservices/profile/src/services/ProfileService.ts
> +    const id = (<{ id: string }>jwt.decode(token))?.id;
Idk I would check the token anyway, what if the request didn't come from the gateway somehow? Maybe an unlikely scenario but I would prefer to check any input to a specific microservice independently

2022-08-22 09:42 UTC, GluterusMaximus commented on server/microservices/profile/src/services/ProfileService.ts
> +    const id = (<{ id: string }>jwt.decode(token))?.id;
If you think this is unnecessary, leave it as is

2022-08-22 09:55 UTC, GluterusMaximus commented on server/microservices/profile/src/models/interfaces/ProfileContacts.ts
> +}
Oh, didn't notice we don't have a Contacts table. Then this makes sense probably. But I don't think we need a profileContact id, just make profileId + contactId the primary key

2022-08-23 17:11 UTC, Secret333Boy commented on server/package.json
> +    "sequelize": "^6.21.4"
It is needed for code in lib folder

2022-08-23 17:11 UTC, Secret333Boy commented on server/lib/checkSudoSecret.ts
> +};
Fixed in 7a77652

2022-08-23 17:13 UTC, Secret333Boy commented on server/microservices/profile/src/controllers/ProfileController.ts
> +      res.sendStatus(201);
I think frontend should repeat GET request to get confirmed profile

2022-08-23 17:15 UTC, Secret333Boy commented on server/microservices/profile/src/controllers/ProfileController.ts
> +      res.sendStatus(201);
Although, there is no problem to return the created profile, I will implement it

2022-08-23 17:20 UTC, Secret333Boy commented on server/microservices/profile/src/controllers/ProfileController.ts
> +      res.sendStatus(201);
Fixed in 3b3a502

2022-08-23 17:25 UTC, Secret333Boy commented on server/microservices/profile/src/services/ProfileService.ts
> +    return profile;
Got it

2022-08-23 17:46 UTC, Secret333Boy commented on server/microservices/profile/src/services/ProfileService.ts
> +    return profile;
Fixed in 8efdae6

2022-08-23 17:48 UTC, Secret333Boy commented on server/microservices/profile/src/services/ProfileService.ts
> +    if (body.tag) profile.tag = body.tag;
Now it is validated by sequelize. Later (while refactoring) we will implement validation through [joi](https://www.npmjs.com/package/joi)

2022-08-23 17:51 UTC, Secret333Boy commented on server/microservices/profile/src/routes/profileRouter.ts
> +profileRouter.put('/', profileController.updateProfile);
It combines PUT and PATCH logic. Therefore, it doesn't matter how to name it

2022-08-23 17:51 UTC, Secret333Boy commented on server/microservices/profile/src/services/ProfileService.ts
> +    const id = (<{ id: string }>jwt.decode(token))?.id;
Will be implemented later while refactoring (while improving validation)

2022-08-23 17:56 UTC, Secret333Boy commented on server/microservices/profile/src/services/ProfileService.ts
> +      throw ApiError.badRequest('Missing some fields');
Will be implemented later (while refactoring and improvement of validation with [joi](https://www.npmjs.com/package/joi))

2022-08-23 18:02 UTC, Secret333Boy commented on server/microservices/profile/src/services/ProfileService.ts
> +    profile: IProfile,
Fixed in 043b622

2022-08-23 18:41 UTC, Secret333Boy commented on server/microservices/profile/src/models/interfaces/ProfileContacts.ts
> +}
Fixed in 7fc25eb

2022-08-24 08:01 UTC, GluterusMaximus commented on server/package.json
> +    "sequelize": "^6.21.4"
Maybe Im blind but I don't see where

2022-08-24 08:01 UTC, GluterusMaximus commented on server/microservices/profile/src/services/ProfileService.ts
> +    if (body.tag) profile.tag = body.tag;
No, I mean what if a duplicate tag is used

2022-08-24 08:02 UTC, GluterusMaximus commented on server/microservices/profile/src/routes/profileRouter.ts
> +profileRouter.put('/', profileController.updateProfile);
I don't see any PUT logic. Maybe I don't understand the difference between PATCH and PUT correctly

2022-08-24 08:03 UTC, Secret333Boy commented on server/microservices/profile/src/services/ProfileService.ts
> +    if (body.tag) profile.tag = body.tag;
unique: true in sequelize

2022-08-24 08:04 UTC, Secret333Boy commented on server/microservices/profile/src/routes/profileRouter.ts
> +profileRouter.put('/', profileController.updateProfile);
PUT = change all fields
PATCH = change some fields

2022-08-24 08:06 UTC, Secret333Boy commented on server/package.json
> +    "sequelize": "^6.21.4"
apiErrorMiddleware

2022-08-24 08:31 UTC, GluterusMaximus commented on server/microservices/profile/src/routes/profileRouter.ts
> +profileRouter.put('/', profileController.updateProfile);
Yes, but there can be a patch request with all the fields, then you change all the fields and it's still a patch request.

2022-08-24 08:32 UTC, GluterusMaximus commented on server/microservices/profile/src/routes/profileRouter.ts
> +profileRouter.put('/', profileController.updateProfile);
It is a put request only if you delete fields that were not sent

2022-08-24 08:42 UTC, Secret333Boy commented on server/microservices/profile/src/routes/profileRouter.ts
> +profileRouter.put('/', profileController.updateProfile);
> Yes, but there can be a patch request with all the fields, then you change all the fields and it's still a patch request.

That's why put and patch are almost the same

2022-08-24 08:44 UTC, Secret333Boy commented on server/microservices/profile/src/routes/profileRouter.ts
> +profileRouter.put('/', profileController.updateProfile);
Okay, according to [this](https://ru.stackoverflow.com/questions/1057964/%d0%a7%d0%b5%d0%bc-put-%d0%be%d1%82%d0%bb%d0%b8%d1%87%d0%b0%d0%b5%d1%82%d1%81%d1%8f-%d0%be%d1%82-patch) should be PATCH

2022-08-24 08:44 UTC, Secret333Boy commented on server/microservices/profile/src/routes/profileRouter.ts
> +profileRouter.put('/', profileController.updateProfile);
Will fix today

2022-08-24 08:45 UTC, GluterusMaximus commented on server/microservices/profile/src/routes/profileRouter.ts
> +profileRouter.put('/', profileController.updateProfile);
Maybe, but this here is definitely a patch request, not put (field not passed ? leave as before the request)

2022-08-26 00:35 UTC, Secret333Boy commented on server/microservices/profile/src/routes/profileRouter.ts
> +profileRouter.put('/', profileController.updateProfile);
Fixed in 474aa2e

2022-08-26 08:37 UTC, GluterusMaximus approved these changes
Looks good

2022-08-26 08:37 UTC, merged